spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://saigowtham05peddinti_db_user:l5jwHqBb8Y4hhMw0@hcl.azsplow.mongodb.net/food_ordering?retryWrites=true&w=majority&appName=hcl}

server.forward-headers-strategy=framework
